name: Tests

on:
  push:
    branches: [ v2.0.0 ]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # 👈 加这个

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [7.4, 8.0, 8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Install deps
        run: composer install

      - name: PHPUnit
        run: ./vendor/bin/phpunit